### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by mr23** [lupo49/autoit-OutlookReminderFocus#1]
I suggest adding a few wiki lines, similar to my posting of 7/31/2013 at http://answers.microsoft.com/en-us/office/forum/officeversion_other-outlook/outlook-meeting-reminders-and-communicator-ims-do/a906bddd-96c7-4717-80a9-44f8241b18d7?page=9

**Comment by lupo49** [comment]
84966b6524a87f57bb750fc6da50c0999b14b586
