### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ghost** [lupo49/autoit-OutlookReminderFocus#3]
When I right click and choose the compile option I get the following message
Line 1 (File
"C:\Users\myuser\Downloads\OutlookReminderFocus.au3"):

<!DOCTYPE html>
<^ERROR

Error:Unable to parse line.

**Comment by lupo49** [comment]
This line isn't the first line in the script.

Please open the file in an editor and check that is the same as in this repo.

**Comment by ghost** [comment]
There is something funky about the file if I right click and "Save Link as".  So I opened it on the github site itself, copied it and pasted it to my PC.
I compiled it by right clicking and choosing the Compile Script (x64) option,  created the exe and ran it.  I now have an icon in my systray that looks like so.
![2013-11-11_095009](https://f.cloud.github.com/assets/5685107/1513367/963d1642-4ae0-11e3-9dda-58aa49180142.jpg)
I closed and restarted outlook but the reminders window still doesn't come to forefront.

**Comment by lupo49** [comment]
Could you start in the AutoIt Debug Modus and post the Console outputs?

**Comment by ghost** [comment]
Mathias,
Thanks for follow-up.  As it turns out it's working as intended now!  Perhaps a reboot over the weekend made a difference?  Now, it pops up nice and bright in the middle of my monitor and forces me to click on the minimize to get it out of the way.  Just right.
Thanks!
